// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tibkipxkylgtrpqhcmqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpYmtpcHhreWxndHJwcWhjbXFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMTA3OTEsImV4cCI6MjA3Mjg4Njc5MX0.Bt6QS7Ba0ZHGjUX8aJr35FyNndvXfHB_sR3R4Y_oCM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});